server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/auth_service_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: mL6vS7Aq8Q2kJt5WnFz9cVxRbY4PpH1NuEoK3sG8LdJwT2yQmZ7BaR6XcF9ViU0eHnP4YgK1dLs8RwM2qZx5NcA==
  expiration: 3600000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

