spring.application.name=bankchain-backend
server.port=8081

# ==========================
# H2 Database Configuration
# ==========================

spring.datasource.url=jdbc:h2:file:./data/bankchain_db;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ==========================
# JPA
# ==========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ==========================
# H2 Console
# ==========================

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==========================
# Swagger
# ==========================

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# ==========================
# Seed Data
# ==========================

app.seed.enabled=true